apiVersion: v1
kind: Pod
metadata:
  labels:
    run: emqx-pod
  name: emqx
#  namespace: dash-iot
spec:
  containers:
  - image: emqx/emqx
    name: emqx-pod
    securityContext:
      runAsUser: 0
    ports:
    - containerPort: 1883
      name: mqtt
    - containerPort: 8083
      name: http
    - containerPort: 8084
      name: ws
    - containerPort: 8883
      name: mqtts
    - containerPort: 18083
      name: dashboard
    volumeMounts:
      - name: emqx-data
        mountPath: /opt/emqx/data
  volumes:
  - name: emqx-data
    persistentVolumeClaim:
      claimName: emqx-data-pvc
  restartPolicy: Always
