apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-svc
  name: api-svc
spec:
  type: NodePort
  ports:
    - name: port
      port: 3030
      protocol: TCP
      targetPort: 3030
      nodePort: 30055
  selector:
    app: api-dash
