apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-dash
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/theautomationrules/nginx-demo-arm:~0.1
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: dash-iot
  source:
    repoURL: ${{ vars.REPO_MANIFEST }}
    targetRevision: main
    path: ./k8s/api-dash
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ vars.NAMESPACE }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
