name: Docker image Api-Dash
# on:
#   workflow_run:
#     workflows: ["Varibles K8S"]
#     types:
#       - completed
#   push:
#     paths: 
#       - '.github/workflows/api-docker-image.yml'
#       - 'api/**'
jobs:
  Build:
    name: Builder Image Api
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login a GitHub Container Register
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push "API" to docker
        uses: docker/build-push-action@v3
        with:
          file: ./api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/api_dash:${{ github.sha }}
            ghcr.io/${{ github.repository }}/api_dash:latest
          context: ./api
      - name: Trigger workflow in another repository
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ vars.REPO_NAME_MANIFEST }}
          event-type: trigger-workflow
          client-payload: '{"image_tag": "ghcr.io/${{ github.repository }}/api_dash:${{ github.sha }}"}'      