name: GitHub CI/CD
on: [push]
jobs:
  environment:
    name: Preparacion de entorno
    runs-on: ubuntu-latest
    steps:
    - name: Conexion a k8s
      run: |
          mkdir -p ${HOME}/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ${HOME}/.kube/config
          kubectl config use-context do-nyc1-k8s-carlosvivas
    - name: Verificacion de ArgoCD
      run: echo "hola mundo"