name: Varibles K8S
# on:
#   push:
#     paths: 
#       - '.github/workflows/variables-k8s.yml'
jobs:
  Build:
    name: Variables for k8s
    runs-on: ubuntu-latest
    steps:
      - name: Connection to k8s
        run: |
          mkdir -p ${HOME}/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ${HOME}/.kube/config
          cat ${HOME}/.kube/config
          kubectl config use-context do-nyc1-k8s-carlosvivas
      - name: Create secret variables 
        run: |
          if kubectl get secret env-secret-k8s -n "${{ vars.NAMESPACE }}" > /dev/null 2>&1; then
            echo "Variables desactualizadas, eliminando..."
            kubectl delete secret env-secret-k8s -n "${{ vars.NAMESPACE }}"
          fi
          echo "Actualizando nuevas varaibles..."
          kubectl create secret generic env-secret-k8s -n "${{ vars.NAMESPACE }}" \
            --from-literal=API_PORT="${{ vars.API_PORT }}"\
            --from-literal=POSTGRES_USER="${{ vars.POSTGRES_USER }}" \
            --from-literal=POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
            --from-literal=POSTGRES_HOST="${{ vars.POSTGRES_HOST }}" \
            --from-literal=POSTGRES_PORT="${{ vars.POSTGRES_PORT }}" \
            --from-literal=POSTGRES_DB="${{ vars.POSTGRES_DB }}"\
            --from-literal=BROKER_PROTOCOL="${{ vars.BROKER_PROTOCOL }}" \
            --from-literal=BROKER_HOST="${{ vars.BROKER_HOST }}" \
            --from-literal=BROKER_PORT="${{ vars.BROKER_PORT }}"\
            --from-literal=BROKER_USER="${{ vars.BROKER_USER }}" \
            --from-literal=BROKER_PASS="${{ secrets.BROKER_PASS }}"